@Server_HostAddress = http://localhost:5000

###
GET {{Server_HostAddress}}/hi
###
GET {{Server_HostAddress}}/chat
###
GET {{Server_HostAddress}}/chat/audrey?message=Hello%20There
###
GET {{Server_HostAddress}}/shutdown
###
GET {{Server_HostAddress}}/ws